### ISSUE TITLE
replicate the updated Rolnick model

### ISSUE THREAD

**Issue by KatrionaGoldmann** [AMI-system/gbif-species-trainer-AMI-fork#2]
Add [pytorch based model](https://github.com/RolnickLab/gbif-species-trainer/blob/master/model_training/04-train_model.py) to model sub-directory

**Comment by LevanBokeria** [comment]
Updated the issue name to reflect the goal of replicating the Rolnick model exactly, with the same dataset they mention in READMEs.

**Comment by KatrionaGoldmann** [comment]
Currently running using CPUs on baskerville, but then running into memory and/or time capacity issues. 

New issue opened: [Run models on baskerville with GPU/CUDA#17](https://github.com/AMI-trap/on_device_classifier/issues/17) to resolve improve the time capacity barrier

**Comment by KatrionaGoldmann** [comment]
Much faster now using GPUs. Model is predicted to run to completion in around 2.5 hours, however we run into disk quota issues.

**Comment by KatrionaGoldmann** [comment]
Model running in https://github.com/AMI-trap/on_device_classifier/pull/19

**Comment by KatrionaGoldmann** [comment]
We can achieve similar accuracies using the increased number of images (aim for 1000 per species). 

Models run for:
- UK
- Singapore
- Costa Rica

See https://github.com/AMI-trap/on_device_classifier/commit/6919a39cdbf900407dc605414067769a76084c04
